language: android
jdk: oraclejdk8
sudo: false
addons:
  sonarcloud:
    organization: "sa-radiotour"
    token:
      secure: "378979c462e37cdde726e8227e204ceb5b6e65ee"
android:
  licenses:
    - android-sdk-license-.+
    - '.+'
  components:
  - platform-tools
  - tools
  - build-tools-25.2.3
  - android-24
  - extra-android-m2repository
before_install:
- chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid warning
install:
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2",
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2",
branches:
  only:
  - master
script:
- "./gradlew build assembleRelease"
- ./gradlew sonarqube
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - '.gradle'
after_success:
- sh set_tags.sh
deploy:
  provider: releases
  api_key:
    secure: pTVQMzZMBeOuWdA9fIVBb3eQRramWHabu9MekTMh0WaujeXUWpbsNGNxnRRCFDusvfgYlbg7D53QUuphnbXlHutOI+NkSQu+3VctjLt+immd2f6aplbQeHQ+w2upF4GQOXj//pnfhtw+uXa6eRtmRUdSEo7/EuCbLQjWIMoLMOCd5h/X+xZELO7XEEQhW0+Rfq8AfpnsPaDyNLEeRX3JPGgFvBV3DB0d4+1/yQ0+9oE1ghdWOdv0WmGoDkHNaOG1wDNnfiAG/OLJgNCampKMCf+XdzCTFE/lnLHQj2BjGpMs0bkNl2vMveZQe2YlsVQe2g5d56RbaZgBUnCHl/9YzTfF3kGYGOb5zRMp9vNsL1FmPQPGOXzhTw1/6GrRlKvqez78LjVglJ98G+XvF5hbrBPCq+MFUnAIwL68ZRRp64U9RblBPd6O1/ciQb00uqtxCyeUmf2vXUwwc2/uvraySSvYPwZEATIw2g0kB+x+tOQTCWHdquIEvTvyINGz3wWtLZXfGh2ym7b8KD1OzGbK6fehbAFxWOf4hxPeyIGk3soZomBq/4czsRamyPWp9o9rfjNtqr0fRUyamZpWJQlqAsnltlRND4RxSwc08hCpM8fhg78ohoS56jj8AiXBlH4xTFfdTJezqor6G6FUyGnvUFEEvCkkgzEGXISjb5FSbs4=
  file: app/build/outputs/apk/RadioTour_V0_${TRAVIS_BUILD_NUMBER}.apk
  file_glob: 'true'
  skip_cleanup: true
  on:
    branch: master
    repo: RadioTour/app
